config/routes.rb
Rails.application.routes.draw do
  resources :blockings
  resources :notifications
  resources :favoris
  resources :flirts
  get 'cgu' => "pages#cgu", as: :cgu
  get 'cookies' => "pages#cookies", as: :cookies
  get 'advertise' => "pages#advertise", as: :advertise
  get 'send/flirt/request/:slug' =>  "flirts#send_flirt", as: :send_new_flirt
  get 'accept/flirt/request/:identifier' =>  "flirts#accept_flirt", as: :accept_flirt
  get 'remove/flirt/request/:identifier' =>  "flirts#remove_flirt", as: :remove_flirt
  get 'add/favoris/request/:slug' =>  "favoris#add_to_favoris", as: :add_to_favoris
  get 'remove/favoris/request/:identifier' =>  "favoris#remove_to_favoris", as: :remove_to_favoris

  #get 'policy'
  resources :messages
  resources :conversations
  # Default routes.
  #root 'home#index'

  get 'home' => 'profiles#index', as: :profile


  # For profiles resources.
  get "/me/:slug" => "profiles#show_his_profile", as: :show_my_profile # After i would replace :login by slug
  get "/me/:slug/presentation" => "profiles#profile_presentation", as: :get_profile_presentation # After i would replace :login by slug
  #post "/me/:slug/presentation" => "profiles#update_profile_presentation", as: :post_profile_presentation # After i would replace :login by slug
  patch "/me/:slug/presentation" => "profiles#update_profile_presentation", as: :update_profile_presentation # After i would replace :login by slug
  get "/me/:slug/informations" => "profiles#profile_informations", as: :get_profile_informations # After i would replace :login by slug
  patch "/me/:slug/informations" => "profiles#update_profile_informations", as: :update_profile_informations # After i would replace :login by slug
  get "/me/:slug/thumbnail" => "profiles#profile_thumbnail", as: :get_profile_thumbnail # After i would replace :login by slug
  patch "/me/:slug/thumbnail" => "profiles#update_profile_thumbnail", as: :update_profile_thumbnail # After i would replace :login by slug

  #get "update/me/:slug" => "profiles#show_his_profile", as: :show_my_profile # After i would replace :login by slug

  get "/profile/:slug" => "profiles#show_his_profile", as: :show_his_profile # After i would replace :login by slug
 # get "update/profile/:slug" => "profiles#show_his_profile", as: :show_his_profile # After i would replace :login by slug

  get "message/new/:recipient_id/" => "messages#new", as: :send_new_message
  get "messages/:identifier/:slug/" => "messages#show", as: :show_messages
  post "message/create/:recipient_id/" => "messages#create", as: :create_message
  
  
  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root 'users/registrations#new', as: :unauthenticated_root
    end
  end

  #devise_for :users

  devise_for :users, path: '', controllers: { 
            registrations: "users/registrations",
            confirmations: 'users/confirmations',
            passwords: "users/passwords",
            sessions: "users/sessions"
            
        }, 
        path_names: {
            sign_in: 'login', 
            sign_out: 'logout', 
            password: 'secret', 
            confirmation: 'verification', 
            unlock: 'unblock', 
            registration: 'signup', 
            sign_up: '' ,
            omniauth_callbacks: 'users/omniauth'
        }



		# Dynamic error pages
		get "/404", to: "errors#not_found"
		get "/422", to: "errors#unacceptable"
		get "/500", to: "errors#internal_error"
end

app/models/conversation.rb
# == Schema Information
#
# Table name: conversations
#
#  id           :bigint           not null, primary key
#  sender_id    :bigint           not null
#  recipient_id :bigint           not null
#  identifier   :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Conversation < ActiveRecord::Base
	# Include shared utils.
	include SharedUtils::Model
   
	before_save :generate_random_number_uid
	
	belongs_to :sender, :foreign_key => "sender_id", :class_name => "User"
 	belongs_to :recipient, :foreign_key => "recipient_id", :class_name => "User"
	
	has_many :messages, dependent: :destroy

	validates_uniqueness_of :sender_id, :scope => :recipient_id
	#validates :identifier, presence: true, uniqueness: true



	private
	def self.get_conversation(user_id)
		where("recipient_id = ? ",user_id)
	end

	def self.current_user_conversations(user_id)
		where("recipient_id = ? OR sender_id = ? ",user_id, user_id)
	end

	def self.own_conversations(user_id)
		where("recipient_id = ? OR sender_id = ? ",user_id, user_id)
	end

	def self.foreign_conversations(user_id)
		where("recipient_id <> ? OR sender_id <> ? ",user_id, user_id)
	end

	# Scope to check reciproque connectivity
	scope :between, -> (sender_id,recipient_id) do
 		where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
 	end


end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

	 before_action :authenticate_user!
	layout "profile"

	 def index
		@conversations = Conversation.current_user_conversations(current_user.id)#.where.not(["sender_id = ? OR recipicient_id = ?", current_user.id, current_user.id])
		
		@conversation_users = []
		
		@conversations.each do |conversation|
			if conversation.sender_id != current_user.id 
				user = User.find(conversation.sender_id)
				@conversation_users.push(user)
			end
			if  conversation.recipient_id != current_user.id 
				user = User.find(conversation.recipient_id)
				@conversation_users.push(user)
			end
		end

		 #@last_unread_conversation =  Conversation.my_conversation(current_user.id)
		 

	 end

	 def show 
		conversations = Conversation.current_user_conversations(current_user.id)
		@conversations_list = []

		conversations.each do |conversation|
			if conversation.sender_id != current_user.id 
				@conversations_list.push(User.find(conversation.sender_id))
			end
			if conversation.recipient_id != current_user.id 
				@conversations_list.push(User.find(conversation.recipient_id))
			end
		end
	 end

	def create
		# Check, if it's exist an conversation or not.
		 if Conversation.between(params[:sender_id],params[:recipient_id]).present?
		    @conversation = Conversation.between(params[:sender_id],params[:recipient_id]).first
		 else
		 	# Create a new conversation before
		  	@conversation = Conversation.create!(conversation_params)

		 end
		 

		  # Create a new message with this conversation.
		 @conversation.messages.create!(message_params)

		 flash[:notice] = "Message envoyé avec succèss!"

		 # Send notification
        content = "Vous avez recu un nouveau message!"
        Notification.create(:content => content, :sender_id => params[:sender_id], :receiver_id => params[:recipient_id])


		 # Redirect to
		 redirect_to profil_path(u: params[:recipient_id])
	end

	# For Tchat
	def tchat
		# Retrieve Sender.
		sender = params[:sender_id] if params[:sender_id]
		
		# Retrieve recipient.
		recipient = params[:recipient_id] if params[:recipient_id]

		# Check conversation (if it exist)
		if Conversation.between(sender, recipient).present?

			#Stored the converation.
			@conversation = Conversation.between(sender,recipient).first

			#flash[:notice] = "Il existe déjà une conversation" if @conversation.present?


		else
			# Creating a new conversation between both.
			@conversation = Conversation.create!(conversation_params)
			flash[:notice] = "Nouvelle conversation créee" if @conversation.save
		end

		# Loading the messages of this conversation.
		@conversation_messages = @conversation.messages

		# Loading current user all conversations.
		@current_user_conversations = Conversation.current_user_conversations(current_user.id).order(:created_at => 'DESC')
	end

	# For reply.
	def reply
		conversation = Conversation.find(params[:conversation_id])
		conversation.messages.create!(message_params)
		#redirect_to conversations_path
		
	end

	# private methode zone. 
	private
	 def conversation_params
	  params.permit(:sender_id, :recipient_id)
	 end

	 def message_params
	 	params.permit(:body, :user_id)
	 end

end

app/views/conversations/_reply.html.erb
<% @messages.each do |m|  %>
					        				<% @me = m.user_id %>
					        				<% @conversation_id = m.conversation_id %>
					        				<% if m.user_id != current_user.id %>
					        						
					        					<div class="row" >
					        						<div class="col-md-1">
														<div class="recipient-image">
															<% get_user_image(m.conversation_id) %>
															<%= image_tag @recipient.thumbnail.url(:medium) %>
														</div>
													</div>
					        						<div class="col-md-11">
							        					<div class="reception">
															<div class="message-body">
																<%= m.body %>
															</div>
															<i class="created-at">
																<%= strtime(m.created_at) %>
															</i>
														</div>
													</div><!-- end col -->
												</div><!-- end row -->
													
											<% else %>

												<div class="row">
													<div class="col-md-11">
														<div class="sended">
															<div class="message-body">
																<%= m.body %>
															</div>
															<i class="created-at">
																<%= strtime(m.created_at) %>
															</i>
														</div>
													</div><!-- end col -->
													<div class="col-md-1">
														<div class="sender-image">
															<% get_user_image(m.conversation_id) %>
															<%= image_tag @sender.thumbnail.url(:medium) %>
														</div>
													</div><!-- end col -->	
												</div><!-- end row -->			
											<% end %>
										<% end %>

app/views/conversations/index.html.erb
<!-- Fil d'actualité -->
<div class="newsfeed">
    <div class="container">
        <div class="card">
            <div class="card-header">
                <strong>Conversations</strong>
            </div>
            <div class="card-body">
                <div class="row">
                    <% @conversations.each do |conversation| %>
                        <%= conversation.sender_id %>
                        <%= conversation.recipient_id %>
                    <% end %>
 
                </div>
            </div>
        </div>
    </div>
</div>

app/views/conversations/prece_index.html.erb
	<div class="container">
		<div class="spacer"></div>
	    <div class="row">
	    	<div class="col-md-9">
	    	<div class="panel panel-default">
  			<div class="panel-body">


	    	<!-- Left column -->
	        <div class="col-md-3">
				<div class="discussion-list-header">
					<p>Liste de discussion	</p>
				</div>
				<!-- Discussion list -->
				<div class="discussion-list list-group">
			        
			        	<% if @last_unread_conversation.present? %>
								<% @last_unread_conversation.each do |c| %>
									<%= link_to(messages_path(id: c), class:"list-group-item")  do %>
					        	
											<div class="col-xs-3">
												<%= image_tag get_user(c.sender_id).thumbnail.url(:medium)  %>
											</div>

											<div class="col-xs-9">
												<p class="">
													<%= user_id_to_name(c.sender_id) %>
																	
												</p>
												<p>
													<% get_last_message(c.id) %>
													<% if @last_message.read == false %>
															<b> <%= @last_message.body %></b>
														<% else %>
															<%= @last_message.body %>
														<% end %>
												</p>
													
											</div>
										

									<% end %><!-- end -->
								<% end %>
						<% end %><!-- end link -->

					  
				</div>
				<!-- end discussion list -->

			</div>


	    	<div class="col-md-9">
			    <div class="msgheader">
			     		
			    </div>
			    <div class="row">
					<div class="discussion-box">
						<div id="message-box" >
							<div class="text-center">
				        		<div class="col-md-9 imgBorders">
			        				<p class="text-center"><i class="fa fa-envelope clrblue"></i></p>
			        				<p class="clrblue medium-font text-center ">Bienvenue  dans votre messagerie</p>
				        		</div>
				        	</div>
						</div>
					</div>
				</div>

				
        	</div> 
        	</div>
        	</div>
        	</div> 
        	<div class="col-md-3">
        	
        	</div>
        </div>
     </div>	
        	 

app/views/conversations/reply.js.erb
$('#message-box').html("<%= escape_javascript (render partial: 'conversations/reply') %>");

app/views/conversations/show.html.erb
<!-- Fil d'actualité -->
<div class="newsfeed">
    <div class="container">
        <div class="card">
            <div class="card-header">
                <strong>Messages</strong>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-3">
                        <div class="left-conversations-list">
                            <% @conversations_list.each do |conversation| %>
                               
                                <ul class="nav flex-column">
                                    <li class="nav-item">
                                        <%= link_to conversation_path(conversation.id), class: "nav-link" do %>   
                                            <!-- Avatar -->
                                            <span class="user-avatar">
                                                <%= user_avatar(conversation, "Avatar", "img-fluid rounded-circle")%>              
                                            </span>
                                        
                                            <!-- Username --->
                                            <span class="user-login">
                                                   <%= conversation.login %> 
                                            </span>
                                        <% end %>
                                        
                                    </li>
                                </ul>

                            <% end %>
                        </div>
                    </div>
                    <div class="col-md-9">
                    </div>
 
                </div>
            </div>
        </div>
    </div>
</div>

app/views/conversations/tchat.html.erb
<div class="spacer"></div>
<div class="container " >
    <div class="col-md-9">
    <div class="chat-wrap">
        <div id="chat" class="chat" style="height: 230px;">
            <div class="left-col">
                <div class="left-cont-contr">
                    <div class="left-cont-contr-head">
                        Messages        
                    </div>
                    <div class="msg-list-header-order thread-cont-sw">
                        <div class="msg-list-header-order-sw" data-title="Trier par">
                            <a data-order="1" class="" do-click="changeOrderThread">non lu</a>
                            <a data-order="2" class="active" do-click="changeOrderThread">dernier</a>
                        </div>
                    </div>
                    <div class="thread-list-tabs">
                        <a data-tabs="1" class="thread-list-tab-item active" do-click="changeOrderThread">Tous</a>
                        <a data-tabs="2" class="thread-list-tab-item" do-click="changeOrderThread">Dialogues</a>
                    </div>
                </div>

                <div class="contacts-list-wrap-scroll">
                    <div class="contacts-list" id="contactListWrapper">            
                        <div class="contact fast online item_235115811 active" data-id="235115811">
                            <button class="close" do-click="closeButtonHandler" data-id="235115811"></button>
                            <div class="cont-type">
                            </div>

                            <% @current_user_conversations.each do |conversation| %>
                                <% if conversation.sender_id == current_user.id %>

                                    <%= link_to(conversations_path(:sender_id => conversation.sender_id, :recipient_id => conversation.recipient_id)) do %>
                                        <div alt="images" class="avatar" title="<%= user_id_to_name(conversation.recipient_id) %>">
                                            <div class="avatar-placeholder ">
                                                <%= image_tag get_user(conversation.recipient_id).thumbnail.url(:medium)  %>
  
                                            </div>
                                            <span class="status"></span>
                                        </div>
                                        <div class="contact-inner">
                                            <div class="author">
                                                <div class="name">
                                                    <%= user_id_to_name(conversation.recipient_id) %>
                                                </div>

                                            </div><!-- / author -->
                                            <div class="contact-message-preview" data-type="1">
                                                <%= last_message(conversation.id) if last_message(conversation.id).present? %>
                                            </div>
                                        </div>
                                    <% end %>
                                <% elsif conversation.recipient_id == current_user.id %>
                                    <%= link_to(conversations_path(:sender_id => conversation.sender_id, :recipient_id => conversation.recipient_id)) do %>
                                        <div alt="images" class="avatar" title="Jolie Ndiaye">
                                            <div class="avatar-placeholder ">  
                                                <%= image_tag get_user(conversation.sender_id).thumbnail.url(:medium)  %>

                                            </div>
                                            <span class="status"></span>
                                        </div>
                                        <div class="contact-inner">
                                            <div class="author">
                                                <div class="name">
                                                    <%= user_id_to_name(conversation.sender_id) %>
                                                </div>

                                            </div><!-- / author -->
                                            <div class="contact-message-preview" data-type="1">
                                                <%= last_message(conversation.id) if last_message(conversation.id).present? %>
                                            </div>
                                        </div>
                                    <% end %>

                                <% end %>
                            <% end %>

                        </div><!-- / contact -->
        
                    </div>
                </div>
            </div><!-- / left-col -->
            <div class="rigt-col">
                <div class="chat-frame" qa-thread-id="235115811" style="background-image: url('https://static.hitwe.com/common/bg_patterns/2_alpha_icons_pattern.png')">
                    <div class="contact-details-wrap">
                        <div class="contact-details-hold">
                            <div class="contact-details user-info online">
                                <div class="contact-user-info-group">
                                    <div class="avatar-big">
                                        <a href="/u235115811">
                                            <div class="avatar-placeholder">
                                                    <% get_user_image(@conversation.id) %>

                                            </div>
                                        </a>
                                        <span class="status"></span>
                                    </div>
                                    <div class="details">
                                        <div class="in-chat">in chat</div>
                                        <%= link_to(profile_path(slug: @recipient.slug, pseudo: @recipient.pseudo)) do %>
                                            <div class="name">
                                                <%= @recipient.pseudo  %>
                                            </div>
                                        <% end %>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                <div class="chat-area" style="height: 351px;">
                    <div id="activity" class="activity" async-container-chat="">    
                        <div class="chat-item-top-placeholder"></div>
                            <% @conversation_messages.each do |message| %>
                                <% if message.user_id == current_user.id %>
                                    <div class="chat-item mine" data-type="1">
                                        <div class="message">
                                            <div class="text">
                                                <%= message.body %>
                                            </div>
                                            <div class="message-detail">
                                                <span>Me</span> | <span>il ya</span>
                                            </div>
                                        </div>
                                        <div class="item-clear">
                                        </div>
                                    </div>
                                <% else %>
                                    <div class="chat-item " data-type="1">
                                        <div class="message">
                                            <div class="text">
                                                <%= message.body %>
                                            </div>
                                            <div class="message-detail">
                                                <span>Jolie Ndiaye</span> | <span>il y a environ une demi-heure</span>
                                            </div>
                                        </div>
                                        <div class="item-clear"></div>
                                    </div>
                                <% end %>
                            <% end %>

                        </div>
                    </div>
                    <div class="chat-form">
                        <div class="chat-info">
                            <div class="chat-read-status hidden" do-click="chatStatusElClick" txt-promo="Find out when read?" txt-read="Read" txt-not-read="Delivered" txt-read-time="">
                            </div>
                        </div>
                        <div class="message-error">
                        </div>
                        <div id="typing" class="typing"><img src="https://static.hitwe.com/hitwe/images/fresh/fancybox_loading_s.gif">
                        </div>
                        <div class="chat-tabs-wrap">
                            <div class="chat-tab active" id="inp-txt">
                           

                                <%= form_tag(reply_message_path, method: 'get', remote: true, id:"message-form") do  %>
                                    <div class="message-wrap">
                                        <div class="form-group">            
                                            <%= text_area_tag :body, params[:body], rows: "2", placeholder: "Votre réponse ici" ,class: "form-controls",required: true %>
                                            <%= text_field_tag :recipient_id, params[:recipient_id], value: @me, type: "hidden" %>
                                            <%= text_field_tag :sender_id, params[:recipient_id], value: current_user.id, type: "hidden" %>
                                            <%= text_field_tag :user_id, params[:user_id], value: current_user.id, type: "hidden" %>
                                            <%= text_field_tag :conversation_id, params[:conversation_id], value: @conversation_id, type: "hidden" %>
                                        </div>
                                        <div class="btns-align-right">
                                            <%= submit_tag 'Répondre',  class: "btn btn-success pull-right" %>                          
                                        </div>
                                    </div>
                                <% end %>

                            </div>
                        </div>
                    </div>
                </div><!-- / chat-form -->
            </div>        
        </div>
    </div>
    </div>
    <div class="col-md-3">
    </div>
</div>