config/routes.rb
Rails.application.routes.draw do
  resources :blockings
  resources :notifications
  resources :favoris
  resources :flirts
  get 'cgu' => "pages#cgu", as: :cgu
  get 'cookies' => "pages#cookies", as: :cookies
  get 'advertise' => "pages#advertise", as: :advertise
  get 'send/flirt/request/:slug' =>  "flirts#send_flirt", as: :send_new_flirt
  get 'accept/flirt/request/:identifier' =>  "flirts#accept_flirt", as: :accept_flirt
  get 'remove/flirt/request/:identifier' =>  "flirts#remove_flirt", as: :remove_flirt
  get 'add/favoris/request/:slug' =>  "favoris#add_to_favoris", as: :add_to_favoris
  get 'remove/favoris/request/:identifier' =>  "favoris#remove_to_favoris", as: :remove_to_favoris

  #get 'policy'
  resources :messages
  resources :conversations
  # Default routes.
  #root 'home#index'

  get 'home' => 'profiles#index', as: :profile


  # For profiles resources.
  get "/me/:slug" => "profiles#show_his_profile", as: :show_my_profile # After i would replace :login by slug
  get "/me/:slug/presentation" => "profiles#profile_presentation", as: :get_profile_presentation # After i would replace :login by slug
  #post "/me/:slug/presentation" => "profiles#update_profile_presentation", as: :post_profile_presentation # After i would replace :login by slug
  patch "/me/:slug/presentation" => "profiles#update_profile_presentation", as: :update_profile_presentation # After i would replace :login by slug
  get "/me/:slug/informations" => "profiles#profile_informations", as: :get_profile_informations # After i would replace :login by slug
  patch "/me/:slug/informations" => "profiles#update_profile_informations", as: :update_profile_informations # After i would replace :login by slug
  get "/me/:slug/thumbnail" => "profiles#profile_thumbnail", as: :get_profile_thumbnail # After i would replace :login by slug
  patch "/me/:slug/thumbnail" => "profiles#update_profile_thumbnail", as: :update_profile_thumbnail # After i would replace :login by slug

  #get "update/me/:slug" => "profiles#show_his_profile", as: :show_my_profile # After i would replace :login by slug

  get "/profile/:slug" => "profiles#show_his_profile", as: :show_his_profile # After i would replace :login by slug
 # get "update/profile/:slug" => "profiles#show_his_profile", as: :show_his_profile # After i would replace :login by slug

  get "message/new/:recipient_id/" => "messages#new", as: :send_new_message
  get "messages/:identifier/:slug/" => "messages#show", as: :show_messages
  post "message/create/:recipient_id/" => "messages#create", as: :create_message
  
  
  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root 'users/registrations#new', as: :unauthenticated_root
    end
  end

  #devise_for :users

  devise_for :users, path: '', controllers: { 
            registrations: "users/registrations",
            confirmations: 'users/confirmations',
            passwords: "users/passwords",
            sessions: "users/sessions"
            
        }, 
        path_names: {
            sign_in: 'login', 
            sign_out: 'logout', 
            password: 'secret', 
            confirmation: 'verification', 
            unlock: 'unblock', 
            registration: 'signup', 
            sign_up: '' ,
            omniauth_callbacks: 'users/omniauth'
        }



		# Dynamic error pages
		get "/404", to: "errors#not_found"
		get "/422", to: "errors#unacceptable"
		get "/500", to: "errors#internal_error"
end

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id           :bigint           not null, primary key
#  title        :string
#  content      :string
#  sender_id    :bigint           not null
#  recipient_id :bigint           not null
#  read         :boolean          default(FALSE)
#  read_at      :datetime
#  status       :string
#  identifier   :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Notification < ApplicationRecord
    # Include shared utils.
   include SharedUtils::Model
   
   before_save :generate_random_number_uid
   
    belongs_to :sender, :foreign_key => "sender_id", :class_name => "User"
    belongs_to :recipient, :foreign_key => "recipient_id", :class_name => "User"

    #validates :identifier, presence: true, uniqueness: true

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:title, :content, :sender_id, :recipient_id, :status)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_with(model: notification, local: true) do |form| %>
  <% if notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :sender_id %>
    <%= form.number_field :sender_id %>
  </div>

  <div class="field">
    <%= form.label :recipient_id %>
    <%= form.number_field :recipient_id %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notifications</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Sender</th>
      <th>Recipient</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.title %></td>
        <td><%= notification.content %></td>
        <td><%= notification.sender_id %></td>
        <td><%= notification.recipient_id %></td>
        <td><%= notification.status %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @notification.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @notification.content %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @notification.sender_id %>
</p>

<p>
  <strong>Recipient:</strong>
  <%= @notification.recipient_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @notification.status %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>