config/routes.rb
Rails.application.routes.draw do
  resources :blockings
  resources :notifications
  resources :favoris
  resources :flirts
  get 'cgu' => "pages#cgu", as: :cgu
  get 'cookies' => "pages#cookies", as: :cookies
  get 'advertise' => "pages#advertise", as: :advertise
  get 'send/flirt/request/:slug' =>  "flirts#send_flirt", as: :send_new_flirt
  get 'accept/flirt/request/:identifier' =>  "flirts#accept_flirt", as: :accept_flirt
  get 'remove/flirt/request/:identifier' =>  "flirts#remove_flirt", as: :remove_flirt
  get 'add/favoris/request/:slug' =>  "favoris#add_to_favoris", as: :add_to_favoris
  get 'remove/favoris/request/:identifier' =>  "favoris#remove_to_favoris", as: :remove_to_favoris

  #get 'policy'
  resources :messages
  resources :conversations
  # Default routes.
  #root 'home#index'

  get 'home' => 'profiles#index', as: :profile


  # For profiles resources.
  get "/me/:slug" => "profiles#show_his_profile", as: :show_my_profile # After i would replace :login by slug
  get "/me/:slug/presentation" => "profiles#profile_presentation", as: :get_profile_presentation # After i would replace :login by slug
  #post "/me/:slug/presentation" => "profiles#update_profile_presentation", as: :post_profile_presentation # After i would replace :login by slug
  patch "/me/:slug/presentation" => "profiles#update_profile_presentation", as: :update_profile_presentation # After i would replace :login by slug
  get "/me/:slug/informations" => "profiles#profile_informations", as: :get_profile_informations # After i would replace :login by slug
  patch "/me/:slug/informations" => "profiles#update_profile_informations", as: :update_profile_informations # After i would replace :login by slug
  get "/me/:slug/thumbnail" => "profiles#profile_thumbnail", as: :get_profile_thumbnail # After i would replace :login by slug
  patch "/me/:slug/thumbnail" => "profiles#update_profile_thumbnail", as: :update_profile_thumbnail # After i would replace :login by slug

  #get "update/me/:slug" => "profiles#show_his_profile", as: :show_my_profile # After i would replace :login by slug

  get "/profile/:slug" => "profiles#show_his_profile", as: :show_his_profile # After i would replace :login by slug
 # get "update/profile/:slug" => "profiles#show_his_profile", as: :show_his_profile # After i would replace :login by slug

  get "message/new/:recipient_id/" => "messages#new", as: :send_new_message
  get "messages/:identifier/:slug/" => "messages#show", as: :show_messages
  post "message/create/:recipient_id/" => "messages#create", as: :create_message
  
  
  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root 'users/registrations#new', as: :unauthenticated_root
    end
  end

  #devise_for :users

  devise_for :users, path: '', controllers: { 
            registrations: "users/registrations",
            confirmations: 'users/confirmations',
            passwords: "users/passwords",
            sessions: "users/sessions"
            
        }, 
        path_names: {
            sign_in: 'login', 
            sign_out: 'logout', 
            password: 'secret', 
            confirmation: 'verification', 
            unlock: 'unblock', 
            registration: 'signup', 
            sign_up: '' ,
            omniauth_callbacks: 'users/omniauth'
        }



		# Dynamic error pages
		get "/404", to: "errors#not_found"
		get "/422", to: "errors#unacceptable"
		get "/500", to: "errors#internal_error"
end

app/models/flirt.rb
# == Schema Information
#
# Table name: flirts
#
#  id           :bigint           not null, primary key
#  sender_id    :bigint           not null
#  recipient_id :bigint           not null
#  status       :string           default("pending")
#  accepted_at  :datetime
#  removed_at   :datetime
#  identifier   :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Flirt < ApplicationRecord
    # Include shared utils.
   include SharedUtils::Model
   
   before_save :generate_random_number_uid
   
    belongs_to :sender, :foreign_key => "sender_id", :class_name => "User"
     belongs_to :recipient, :foreign_key => "recipient_id", :class_name => "User"
     
    #validates :identifier, presence: true, uniqueness: true

    def self.current_user_flirts(user_id)
		where("recipient_id = ? OR sender_id = ? ",user_id, user_id)
    end
    
end

app/controllers/flirts_controller.rb
class FlirtsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_flirt, only: [:show, :edit, :update, :destroy]

  # GET /flirts
  # GET /flirts.json
  def index
    @flirts = Flirt.all
  end

  # GET /flirts/1
  # GET /flirts/1.json
  def show
  end

  # GET /flirts/new
  def new
    @flirt = Flirt.new
  end

  # GET /flirts/1/edit
  def edit
  end

  def send_flirt
    recipient = User.find_by(slug: params[:slug])
    if recipient.present?
      flirt = Flirt.new
      flirt.recipient_id = recipient.id
      flirt.sender_id = current_user.id
      flirt.save

      if flirt.save
        redirect_to show_his_profile_path(recipient.slug)
      end
    end
  end

  # POST /flirts
  # POST /flirts.json
  def create
    @flirt = Flirt.new(flirt_params)

    respond_to do |format|
      if @flirt.save
        format.html { redirect_to @flirt, notice: 'Flirt was successfully created.' }
        format.json { render :show, status: :created, location: @flirt }
      else
        format.html { render :new }
        format.json { render json: @flirt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flirts/1
  # PATCH/PUT /flirts/1.json
  def update
    respond_to do |format|
      if @flirt.update(flirt_params)
        format.html { redirect_to @flirt, notice: 'Flirt was successfully updated.' }
        format.json { render :show, status: :ok, location: @flirt }
      else
        format.html { render :edit }
        format.json { render json: @flirt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flirts/1
  # DELETE /flirts/1.json
  def destroy
    @flirt.destroy
    respond_to do |format|
      format.html { redirect_to flirts_url, notice: 'Flirt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flirt
      @flirt = Flirt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flirt_params
      params.require(:flirt).permit(:sender_id, :recipient_id, :status)
    end
end

app/helpers/flirts_helper.rb
module FlirtsHelper
    def is_flirt(user)
        user = User.find_by(slug: user.slug)
        if user.present?
            existing_flirt = find_flirt(user.id)
            if existing_flirt.present? 
                if existing_flirt.status = "pending"
                    "pending"
                elsif existing_flirt.status = "accepted"
                    "accepted"
                end
            end
        end

        
    end

    def find_flirt(recipient_id)
        flirts = Flirt.current_user_flirts(current_user.id)
        if flirts.present?
            flirt = flirts.where(["recipient_id = ? OR sender_id = ?", recipient_id, recipient_id]).take
        end
    end
end

app/views/flirts/_form.html.erb
<%= form_with(model: flirt, local: true) do |form| %>
  <% if flirt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flirt.errors.count, "error") %> prohibited this flirt from being saved:</h2>

      <ul>
      <% flirt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sender_id %>
    <%= form.number_field :sender_id %>
  </div>

  <div class="field">
    <%= form.label :recipient_id %>
    <%= form.number_field :recipient_id %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label : %>
    <%= form.text_field : %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flirts/edit.html.erb
<h1>Editing Flirt</h1>

<%= render 'form', flirt: @flirt %>

<%= link_to 'Show', @flirt %> |
<%= link_to 'Back', flirts_path %>

app/views/flirts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flirts</h1>

<table>
  <thead>
    <tr>
      <th>Sender</th>
      <th>Recipient</th>
      <th>Status</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flirts.each do |flirt| %>
      <tr>
        <td><%= flirt.sender_id %></td>
        <td><%= flirt.recipient_id %></td>
        <td><%= flirt.status %></td>
        <td><%= flirt. %></td>
        <td><%= link_to 'Show', flirt %></td>
        <td><%= link_to 'Edit', edit_flirt_path(flirt) %></td>
        <td><%= link_to 'Destroy', flirt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flirt', new_flirt_path %>

app/views/flirts/new.html.erb
<h1>New Flirt</h1>

<%= render 'form', flirt: @flirt %>

<%= link_to 'Back', flirts_path %>

app/views/flirts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sender:</strong>
  <%= @flirt.sender_id %>
</p>

<p>
  <strong>Recipient:</strong>
  <%= @flirt.recipient_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @flirt.status %>
</p>

<p>
  <strong>:</strong>
  <%= @flirt. %>
</p>

<%= link_to 'Edit', edit_flirt_path(@flirt) %> |
<%= link_to 'Back', flirts_path %>