config/routes.rb
Rails.application.routes.draw do
  resources :blockings
  resources :notifications
  resources :favoris
  resources :flirts
  get 'cgu' => "pages#cgu", as: :cgu
  get 'cookies' => "pages#cookies", as: :cookies
  get 'advertise' => "pages#advertise", as: :advertise
  get 'send/flirt/request/:slug' =>  "flirts#send_flirt", as: :send_new_flirt
  get 'accept/flirt/request/:identifier' =>  "flirts#accept_flirt", as: :accept_flirt
  get 'remove/flirt/request/:identifier' =>  "flirts#remove_flirt", as: :remove_flirt
  get 'add/favoris/request/:slug' =>  "favoris#add_to_favoris", as: :add_to_favoris
  get 'remove/favoris/request/:identifier' =>  "favoris#remove_to_favoris", as: :remove_to_favoris

  #get 'policy'
  resources :messages
  resources :conversations
  # Default routes.
  #root 'home#index'

  get 'home' => 'profiles#index', as: :profile


  # For profiles resources.
  get "/me/:slug" => "profiles#show_his_profile", as: :show_my_profile # After i would replace :login by slug
  get "/me/:slug/presentation" => "profiles#profile_presentation", as: :get_profile_presentation # After i would replace :login by slug
  #post "/me/:slug/presentation" => "profiles#update_profile_presentation", as: :post_profile_presentation # After i would replace :login by slug
  patch "/me/:slug/presentation" => "profiles#update_profile_presentation", as: :update_profile_presentation # After i would replace :login by slug
  get "/me/:slug/informations" => "profiles#profile_informations", as: :get_profile_informations # After i would replace :login by slug
  patch "/me/:slug/informations" => "profiles#update_profile_informations", as: :update_profile_informations # After i would replace :login by slug
  get "/me/:slug/thumbnail" => "profiles#profile_thumbnail", as: :get_profile_thumbnail # After i would replace :login by slug
  patch "/me/:slug/thumbnail" => "profiles#update_profile_thumbnail", as: :update_profile_thumbnail # After i would replace :login by slug

  #get "update/me/:slug" => "profiles#show_his_profile", as: :show_my_profile # After i would replace :login by slug

  get "/profile/:slug" => "profiles#show_his_profile", as: :show_his_profile # After i would replace :login by slug
 # get "update/profile/:slug" => "profiles#show_his_profile", as: :show_his_profile # After i would replace :login by slug

  get "message/new/:recipient_id/" => "messages#new", as: :send_new_message
  get "messages/:identifier/:slug/" => "messages#show", as: :show_messages
  post "message/create/:recipient_id/" => "messages#create", as: :create_message
  
  
  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root 'users/registrations#new', as: :unauthenticated_root
    end
  end

  #devise_for :users

  devise_for :users, path: '', controllers: { 
            registrations: "users/registrations",
            confirmations: 'users/confirmations',
            passwords: "users/passwords",
            sessions: "users/sessions"
            
        }, 
        path_names: {
            sign_in: 'login', 
            sign_out: 'logout', 
            password: 'secret', 
            confirmation: 'verification', 
            unlock: 'unblock', 
            registration: 'signup', 
            sign_up: '' ,
            omniauth_callbacks: 'users/omniauth'
        }



		# Dynamic error pages
		get "/404", to: "errors#not_found"
		get "/422", to: "errors#unacceptable"
		get "/500", to: "errors#internal_error"
end

app/views/layouts/partials/_dashboard_footer.html.erb
<div  class="footer">
  
       
        
        <%= link_to "Conditions générales d'utilisation", cgu_path, title: "Prenez connaissance des conditions générales et des règlements." %>
       
        <span role="presentation" aria-hidden="true"> 
            · 
        </span>
        
        <%= link_to "Publicité", advertise_path, title: "Diffusez votre publicité sur Flirtera."%>

        <span role="presentation" aria-hidden="true"> 
            · 
        </span>
       
        
        <%= link_to "Cookies", cookies_path, title: "Cookies."%>

       
        
        </div>
        <div>
        <span class="profile-sidebar-copyright">
            &copy; Flirtera <%= Time.now.year %>
        </span>
    
</div>

app/views/layouts/partials/_flash_messages.html.erb
<% if flash.present? %>
  <div id='flash'>
   <script>
     <% if flash[:notice] %>
       var $toastContent = $('<span><%= flash[:notice] %></span>');
       toastr.success($toastContent)
     <% end %>
     <% if flash[:warning] %>
       var $toastContent = $('<span><%= flash[:warning] %></span>');
       toastr.info($toastContent)
     <% end %>
     <% if flash[:alert] %>
       var $toastContent = $('<span><%= flash[:alert] %></span>');
       toastr.error($toastContent)
     <% end %>
   </script>
  </div>
<% end %>

app/views/layouts/partials/_footer.html.erb
<div class="footer-one">

	

    <div class="container">
        <div class="row">
			<div class="col-md-6 copyright">
				&copy;  <%= "#{Time.now.year} - #{APPLICATION_NAME}" %>. Tous droits Réservés. 
			</div>

			<div class="col-md-6">
				<div class="social-link">
					<div class="text-center">
	                
	                
	                <a href="https://www.facebook.com/flirtera/" class="btn btn-social-icon btn-facebook" target="_blank"><i class="fa fa-facebook"></i>
	                </a>
	              
	                
	               

	                <a href="https://www.instagram.com/flirtera.official/" class="btn btn-social-icon btn-instagram" target="_blank"><i class="fa fa-instagram"></i></a>

	               
	                <a href="https://twitter.com/Flirtera2" class="btn btn-social-icon btn-twitter" target="_blank"><i class="fa fa-twitter"></i></a>
	                
	              </div>
				</div>
			</div>

		</div>

    </div>
</div>

app/views/layouts/partials/_google_analytics.html.erb
<% if Rails.env.production? %>

  <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-144729623-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-144729623-1');
</script>


<% end %>

app/views/layouts/partials/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark  bg-dark"> <!-- fixed-top -->
	<div class="container">
  
	<div class= "navbar-brand">
		<% if user_signed_in? %>
			<%= link_to profile_path do %>
			<%= image_tag "logo/logo-togglelife-white.png" %> 
			<% end %>

		<% else %>

			<%= link_to unauthenticated_root_url, class: "navbar-brand" do %>
				<%= image_tag "logo/logo-togglelife-white.png" %> 
			<% end %>
	<% end %>
  </div>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav flex-row flex-wrap bd-navbar-nav pt-2 py-md-0">
    <!-- If login -->
    <% if current_user %>
    <!--
    <form class="form-inline my-2 my-lg-0 header_searchbox">
      <input class="form-control mr-sm-2" type="search" placeholder="Rechercher" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa fa-search" aria-hidden="true"></i>
      </button>
    </form> -->
    <% end %>
	</ul> 
	
	<ul class="navbar-nav flex-row flex-wrap ms-md-auto">

		<% if user_signed_in? %>

			<ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">

<!-- Messages notifications -->
<!-- Notifications dropdown -->
     
                
			
        
				
		</ul>


	<!-- User Account Menu -->




<ul>
    <li class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
     <%= user_avatar(current_user, "Avatar", "img-fluid rounded-circle")%>
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <%= link_to "Mon compte" , show_my_profile_path(slug: current_user.slug), class: "dropdown-item" %>
      <div class="dropdown-divider"></div>
      <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete,  class: "dropdown-item"  %>

    </div>
  </li>
</ul>
          

	<% else %>
          <li class="nav-item">
              <%= link_to "Connexion", new_user_session_path,  class:"btn btn-outline-warning" %>
            
          </li>
          <li class="nav-item">
            <%= link_to "Inscription", new_user_registration_path,  class:"btn btn-login" %>
          
        	</li>
          
		 
		  <% end %>
		  </ul>
   
  </div>
  </div>
</nav>

app/views/layouts/partials/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark  bg-dark"> <!-- fixed-top -->
	<div class="container">
  
	<div class= "navbar-brand">
		<% if user_signed_in? %>
			<%= link_to profile_path do %>
			<%= image_tag "logo/logo60.png" %> 
			<% end %>

		<% else %>

			<%= link_to root_url, class: "navbar-brand" do %>
				<%= image_tag "logo/logo60.png" %> 
			<% end %>
	<% end %>
  </div>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <!-- If login -->
    <% if current_user %>
    <!--
    <form class="form-inline my-2 my-lg-0 header_searchbox">
      <input class="form-control mr-sm-2" type="search" placeholder="Rechercher" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa fa-search" aria-hidden="true"></i>
      </button>
    </form> -->
    <% end %>
	</ul> 
	
	<ul class="navbar-nav ml-auto">

		<% if user_signed_in? %>

			<ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">

<!-- Messages notifications -->
<!-- Notifications dropdown -->
     
                
			
        
				
		</ul>


	<!-- User Account Menu -->




<ul>
    <li class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
     <%= user_avatar(current_user, "Avatar", "img-fluid rounded-circle")%>
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <%= link_to "Mon compte" , show_my_profile_path(slug: current_user.slug), class: "dropdown-item" %>
      <div class="dropdown-divider"></div>
      <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete,  class: "dropdown-item"  %>

    </div>
  </li>
</ul>
          

	<% else %>
          <li class="nav-item">
              <%= link_to "Connexion", new_user_session_path,  class:"btn btn-outline-warning" %>
            
          </li>
          <li class="nav-item">
            <%= link_to "Inscription", new_user_registration_path,  class:"btn btn-login" %>
          
        	</li>
          
		 
		  <% end %>
		  </ul>
   
  </div>
  </div>
</nav>

app/views/layouts/partials/_sidebar-old.html.erb
<div class="left-sidebar" role="left-sidebar">

  <div class="card-body">
<div class="act-panel ">
    <div class="act-panel-wr">
        <%= link_to show_my_profile_path(slug: current_user.slug), class: "act-panel-user" do %>
        
            <div class="act-panel-user-pic">
                <div class="act-panel-user-avatar">
                    <div class="avatar-placeholder"> 
                         <%= user_avatar(current_user, "Avatar", "img-fluid rounded-circle")%>
                    </div>                
                </div>
                <div class="act-panel-user-name">
                    <%= current_user.login %>               
                </div>
            </div>
        <% end %>

        <div class="act-main-menu">
            

            
           
            <a href="/messages" class="act-main-menu-item act-main-msg">
                Messages                <div class="act-main-nav-buble empty">0</div>
                <span class="icon">
                <i class="fa fa-comments-o" aria-hidden="true"></i>
                                </span>
            </a>
            <a href="/profile/activity?page=favd" class="act-main-menu-item act-main-like">
                Aimé(e) par                
                
                <span class="icon">
                <i class="fa fa-heart-o" aria-hidden="true"></i>
                </span>
                <div class="act-main-nav-buble empty">0</div>
            </a>
            <a href="/profile/activity?page=visit" class="act-main-menu-item act-main-visitor">
                Visiteurs                
                <span class="icon">
                <i class="fa fa-eye" aria-hidden="true"></i>               
                 </span>
                <div class="act-main-nav-buble empty">0</div>
            </a>
            <a href="/profile/activity?page=mutuals" class="act-main-menu-item act-main-mutuals">
                Goûts en commun                
                <span class="icon">
                <i class="fa fa-heartbeat" aria-hidden="true"></i>                
                 </span>
                <div class="act-main-nav-buble empty">0</div>
            </a>
            
            
            <a href="/messages/contacts" class="act-main-menu-item act-main-contacts">
            <span class="icon">
            <i class="fa fa-users" aria-hidden="true"></i>             </span>
                Contacts            
                </a>
            
            
           
           


        </div>
       

        

    </div>

    
    </div>

    </div>
    </div>
    <div class="footer">
        
                    <%= render 'layouts/partials/dashboard_footer' %>
               
    </div>

app/views/layouts/partials/_sidebar.html.erb
<!-- Profil sidebar -->
<div class="profile-sidebar">
    <!-- Profile sidebar header -->
    <div class="profile-sidebar-header">
        <div class="row">
            <ul class="nav flex-column">
                <li class="nav-item">
                    <%= link_to show_my_profile_path(slug: current_user.slug), class: "nav-link" do %>   
                        <!-- Avatar -->
                        <span class="user-avatar">
                            <%= user_avatar(current_user, "Avatar", "img-fluid rounded-circle")%>              
                        </span>
                    
                        <!-- Username --->
                        <span class="user-login">
                            <%=  current_user.login %> 
                        </span>
                    <% end %>
                    
                </li>
            </ul>
            
        </div>
    </div><!-- end -->

    <!-- Prodile sidebar  !-->
    <div class="profile-sidebar-body">
        <!-- Profile sidebar content-first -->
        <div class="profile-sidebar-content-first">
            <div class="row">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <%= link_to profile_path, class: "nav-link active" do  %>
                             <span class="icon">
                                <i class="fa fa-newspaper-o" aria-hidden="true"></i>                
                             </span>
                             <span>Fil d'actualité</span>
                        <% end %>
                       
                    </li>

                    <li class="nav-item">
                        <%= link_to messages_path, class: "nav-link" do  %>
                             <span class="icon">
                                <i class="fa fa-comments-o" aria-hidden="true"></i>                
                             </span>
                             <span>Messages</span>
                        <% end %>
                       
                    </li>
                   
                   
                    <li class="nav-item">
                        <%= link_to favoris_path, class: "nav-link" do  %>
                             <span class="icon">
                                <i class="fa fa-star-o" aria-hidden="true"></i>                
                             </span>
                             <span>Favoris</span>
                        <% end %>
                       
                    </li>
                    <li class="nav-item">
                        <%= link_to profile_path, class: "nav-link" do  %>
                             <span class="icon">
                                <i class="fa fa-user-o" aria-hidden="true"></i>                
                             </span>
                             <span>Flirts</span>
                        <% end %>
                       
                    </li>
                </ul>
            </div>
        </div>
    </div><!-- end -->
    <!-- Profile sidebar footer -->
    <div class="profile-sidebar-footer">
        <div class="row">
            <%= render 'layouts/partials/dashboard_footer' %>  
        </div>     
    </div>
</div><!-- end profil sidebar -->